#!/usr/bin/env ruby

# Problem: a test failure in the workarea-reviews plugin had eluded us for quite
# a while. During the hustle-n-bustle of the plugin updates at the end of the
# last minor release, the theme plugins just decorated the test. Now that the
# test has been fixed we need to obtain a list of plugins that have decorated
# this test so that we can go and manually edit them.
#
# Adds a file to `/tmp/decorated_tests.log` FYI.
#
# Command to run:
#
# codeslave \
#   --org workarea-commerce \
#   --repo '-theme$' \
#   --branch '(-stable$|^master$)' \
#   --script examples/find_decorated_test \
#   --debug

repo_path, repo_name, branch = ARGV
logfile = File.open("/tmp/decorated_tests.log", 'a')

decorated_files = Dir[[repo_path, '**/reviews_helper_test.decorator'].join('/')]

if decorated_files.empty?
  logfile.close
  abort("File not found in #{repo_path}")
end

file_content = "in: #{repo_name}:#{branch}\n"

logfile.write(file_content)
logfile.close

exit
