name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby_version: 2.6.x
      - name: Install Dependencies
        run: 'gem install bundler && bundle install'
      - name: Run Tests
        run: bundle exec rake
